### PR TITLE
Remove tippy.js

### LINKED ISSUE #69: Remove tippyjs from MenuBar and Action Center
Currently, MenuBar, to show menus, uses TippyJS and lots of state management with Jotai. But that is quite slow.

Goal:
Remove TippyJS from the equation entirely.
Rely on CSS as much as possible, though using Jotai to show stuff actually seems like the best scenario here, as `:hover` will not work unidirectionally, that is, it will show as well as hide on hover and removed-hover, which we do not want.

Same goes for ActionCenter. Use same methods for it too

### PR DESCRIPTION
**Pull request by Aslemammad**
Fix #69. This one removes tippy.js.

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import 'preact/debug';
```
Comment (PuruVJ) [inline src/index.tsx:1]: Hi, pls remove it. `@preact-preset-vite` already handles it and removes it in prod

**Review by PuruVJ — CHANGES_REQUESTED** [review]
First of all, great PR!! Small enough, does the job done really well, and the result is super fast. Zero lag while opening and hovering over the menu buttons. Love it

There's a change I requested. Please do that.

I noticed that the closing animation when a menu is force closed is gone. That is fine. I'd merge this PR without that and fix it later on. However, if you feel like looking into that, great!! I'm happy to merge even if you don't want to :)
